# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">=0.13.0"
  required_providers {

    aws = {
      source  = "hashicorp/aws"
      version = "3.35.0"
    }

    testing = {
      source  = "apparentlymart/testing"
      version = "0.0.2"
    }
  }
}
provider "testing" {}

provider "aws" {
  region  = "us-west-2"
  profile = "sandbox-admin"
}


