repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0 
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terragrunt_validate