version: "3.8"
services:
  testing:
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    build:
      context: ./
    stdin_open: true
    tty: true
    container_name: testing_env
    image: terraform-aws-landing-zone:latest
    volumes:
      - "$PWD:/src"
    command: ["/bin/bash"]